### ISSUE TITLE
For multiproject solution with different build target name mapping, cbuild cannot identify build sequence

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/cbuild#116]
For NXP RT platform multiproject solution, usually cm7 core project target name is not same with cm4 core project target name, like cm7 flexspi_nor_debug work with cm4 debug. And cm7 doesn't have debug target, cm4 does have flexspi_nor_debug target.
Here is the csolution yml:

```
solution:
  created-for: cmsis-toolbox@2.0.0
  packs:
  - pack: NXP::MULTICORE
  - pack: NXP::MIMXRT1176_DFP
  - pack: NXP::MIMXRT1170-EVKB_BSP
  - pack: ARM::CMSIS
  target-types:
  - type: armgcc
    compiler: GCC
  - type: iar
    compiler: IAR
  - type: mdk
    compiler: AC6
  output-dirs:
    outdir: "$ProjectDir()$/$TargetType$/$BuildType$"
  build-types:
  - type: flexspi_nor_debug
    context-map:
    - hello_world_cm4.debug
  - type: flexspi_nor_release
    context-map:
    - hello_world_cm4.release
  - type: debug
    context-map:
    - hello_world_cm7.flexspi_nor_debug
  - type: release
    context-map:
    - hello_world_cm7.flexspi_nor_release
  projects:
  - project: cm4/hello_world_cm4.cproject.yml
    not-for-context:
    - ".flexspi_nor_debug+iar"
    - ".flexspi_nor_release+iar"
    - ".flexspi_nor_debug+mdk"
    - ".flexspi_nor_release+mdk"
    - ".flexspi_nor_debug+armgcc"
    - ".flexspi_nor_release+armgcc"
  - project: cm7/hello_world_cm7.cproject.yml
    not-for-context:
    - ".debug+armgcc"
    - ".release+armgcc"
    - ".debug+mdk"
    - ".release+mdk"
    - ".debug+iar"
    - ".release+iar"
```
When we use cbuild cmd like
```
cbuild hello_world_multicore.csolution.yml --update-rte -c .flexspi_nor_debug+mdk -O /e/open_CMSIS_ws/11151112
```
The cbuild will report such issue:
```
: Could not find incbin file 'core1_image.bin'
        .incbin "core1_image.bin"
```

The core1_image.bin is the output of cm4 debug. In this case, cbuild doesn't get correct build sequence and it doesn't build cm4 target(not sure whether it is because cm7 has built failure), we expect cm4 to be build firstly, then cm7. The sequence is recorded in the csolution project order. 

For platform like lpcxpresso55s69 in which all core project targets are named as "debug", when we run 
```
cbuild hello_world_multicore.csolution.yml --update-rte -c .debug+mdk -O /e/open_CMSIS_ws/11151114
```
core1 and core0 pojects are build with sequence designated in csolution yml and passed.

**Comment by jkrech** [comment]
@tcsunhao , thanks for reporting the issue you are seeing.
Looking at your command line  you specify the contexts
```
-c .flexspi_nor_debug+mdk
```
This means you expect to build the projects
```
hello_world_cm4.cproject.yml
hello_world_cm7.cproject.yml
```
However you have explicitly excluded this project for this build-type target-type combination.
```
 - project: cm4/hello_world_cm4.cproject.yml
    not-for-context:
    - ".flexspi_nor_debug+mdk"
```

If my understanding of the implementation is correct (@brondani, please comment), the whole context processing on the csolution.yml file level only deals with specified target-types and build-types and does not consider the `context-map:` nodes.
Only when the actual processing of the cproject file starts, the target-type and build-type get mapped. 

Processing the csolution.yml for the above command line results in the request to build,
assuming we are removing the `not-for-context:` for `hello_work_cm4`
```
hello_world_cm4.flexspi_nor_debug+mdk
hello_world_cm7.flexspi_nor_debug+mdk
```

The processing of hello_world_cm4.cproject.yml will use the mapped build-type `debug`:
```
hello_world_cm4.debug+mdk
```

**Comment by brondani** [comment]
It seems it is the same example already discussed in https://github.com/Open-CMSIS-Pack/cbuild/issues/99.

**Comment by tcsunhao** [comment]
Hi @brondani , yes, it is the same example already discussed in https://github.com/Open-CMSIS-Pack/cbuild/issues/99, I don't think we have got expectation. So I want to discuss here again. Now our test team has to open the csolution to analyze to get the mapping between projects, then build with 
```
cbuild hello_world_multicore.csolution.yml --update-rte -c .flexspi_nor_debug+mdk,.debug+mdk -O <output_dir>
```
We think this mapping analysis shall be done in cbuild side.

Hi @jkrech , we cannot remove not-for-context for cm4 projects because our cm4 projects really doesn't support the listed targets. We expect cbuild can get build sequence from csolution yml and do the build for all projects of the solution. I think it is a common need for all users as well.

**Comment by jkrech** [comment]
These are the required changes. In the csolution.yml there is only build-type `debug` and `release`
```
solution:
  created-for: cmsis-toolbox@2.0.0
  packs:
  - pack: NXP::MULTICORE
  - pack: NXP::MIMXRT1176_DFP
  - pack: NXP::MIMXRT1170-EVK_BSP
  - pack: ARM::CMSIS
  target-types:
  - type: armgcc
    compiler: GCC
  - type: iar
    compiler: IAR
  - type: mdk
    compiler: AC6
  output-dirs:
    outdir: "$ProjectDir()$/$TargetType$/$BuildType$"
  build-types:
#  - type: flexspi_nor_debug
#    context-map:
#    - rpmsg_lite_pingpong_cm4.debug
#  - type: flexspi_nor_release
#    context-map:
#    - rpmsg_lite_pingpong_cm4.release
  - type: debug
    context-map:
    - rpmsg_lite_pingpong_cm7.flexspi_nor_debug
  - type: release
    context-map:
    - rpmsg_lite_pingpong_cm7.flexspi_nor_release
  projects:
  - project: cm4/rpmsg_lite_pingpong_cm4.cproject.yml
 #   not-for-context:
 #   - ".flexspi_nor_debug+iar"
 #   - ".flexspi_nor_release+iar"
 #   - ".flexspi_nor_debug+mdk"
 #   - ".flexspi_nor_release+mdk"
 #   - ".flexspi_nor_debug+armgcc"
 #   - ".flexspi_nor_release+armgcc"
  - project: cm7/rpmsg_lite_pingpong_cm7.cproject.yml
 #   not-for-context:
 #   - ".debug+armgcc"
 #   - ".release+armgcc"
 #   - ".debug+mdk"
 #   - ".release+mdk"
 #   - ".debug+iar"
 #   - ".release+iar"
```
As a result of the context-map while processing the rpmsg_lite_pingpong_cm7.cproject.yml file the build-type `.debug` is replaced by `.flexspi_nor_debug` when processing `for-context` conditions.
When using access sequences it is probably best to only specify the project and no build-type:
``` 
"-I$OutDir(rpmsg_lite_pingpong_cm4)$" 
```
Invocation of cbuild:
```
  cbuild rpmsg_lite_pingpong.csolution.yml -c .release
```
will first build cm4 release for all toolchains followed by cm7 without the need for the user to understand which contexts belong to each other because that is specified through the `context-map`.
