### ISSUE TITLE
cbuild version 1.6.1 build errors

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/cbuild#60]
![image](https://user-images.githubusercontent.com/3381677/233377070-5a6e3f49-72ee-4e2e-9cac-0751eed2fb46.png)

The setting is like
```
  - setup: AC6
    for-compiler: AC6
    for-type: ".debug"
    misc:
    - C:
      - "-DDEBUG"
      - "-DCPU_MIMXRT1166DVM6A_cm7"
      - "-DPRINTF_FLOAT_ENABLE=0"
      - "-DSCANF_FLOAT_ENABLE=0"
      - "-DPRINTF_ADVANCED_ENABLE=0"
      - "-DSCANF_ADVANCED_ENABLE=0"
      - "-DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1"
      - "-DMCUXPRESSO_SDK"
      - "-g"
      - "-O1"
      - "-mcpu=cortex-m7"
      - "-mfpu=fpv5-d16"
      - "-std=c99"
      - "-fshort-enums"
      - "-fshort-wchar"
      - "-ffunction-sections"
      - "-fno-common"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mthumb"
      - "-fno-rtti"
      ASM:
      - "-DDEBUG"
      - "-D__STARTUP_INITIALIZE_NONCACHEDATA"
      CPP:
      - "-DDEBUG"
      - "-DMCUXPRESSO_SDK"
      - "-g"
      - "-O1"
      - "-mcpu=cortex-m7"
      - "-mfpu=fpv5-d16"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mthumb"
      - "-fno-rtti"
      - "-fno-exceptions"
      Link:
      - "--remove"
      - "--entry=Reset_Handler"
      - "--map"
      - "--xref"
      - "--callgraph"
      - "--symbols"
      - "--info sizes"
      - "--info totals"
      - "--info unused"
      - "--info veneers"
      - "--strict"
      - "--library_type=microlib"
```

For same project, cbuild IAR can build passed. Old version cbuild MDK can build.
