### ISSUE TITLE
[2.1.0][cbuild] critical issue: context-map does not work

### ISSUE THREAD

**Issue by Hoohaha** [Open-CMSIS-Pack/cbuild#99]
Documentation said:

The context-map: node allows for a specific project-name the remapping of target-types: and/or build-types: to a different context.
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.1.0/docs/YML-Input-Format.md#context-map

```yaml
target-types:
    - type: DualCore
      device: MyDualCoreDevice

  build-types:
    - type: Release                        # When applying build-type name 'release':
      context-map:
        - context: HelloCM7.flex_release   # project HelloCM7 uses build-type name "flex_release" instead of "release"
     
  projects:
    - project: ./CM7/HelloCM7.cproject.yml
    - project: ./CM4/HelloCM4.cproject.yml
```

But when add `- context` the cbuild display error:
```yaml
info cbuild: Build Invocation 2.1.0 (C) 2023 Arm Ltd. and Contributors
debug cbuild: CMSIS_PACK_ROOT: C:\Users\NXF60078\AppData\Local\Arm\Packs
debug cbuild: CMSIS_COMPILER_ROOT: C:\Users\NXF60078\AppData\Local\Programs\cmsis-toolbox-windows-amd64\etc
C:/c/pkg/boards/evkbmimxrt1170/multicore_examples/hello_world/hello_world_multicore.csolution.yml:21:9 - error csolution: ba
ersion
error cbuild: exit status 1
```

```yaml

---
solution:
  created-for: cmsis-toolbox@2.0.0
  packs:
  - pack: NXP::MULTICORE
  - pack: NXP::MIMXRT1176_DFP
  - pack: NXP::MIMXRT1170-EVKB_BSP
  - pack: ARM::CMSIS
  target-types:
  - type: armgcc
    compiler: GCC
  - type: iar
    compiler: IAR
  - type: mdk
    compiler: AC6
  output-dirs:
    outdir: "$ProjectDir()$/$TargetType$/$BuildType$"
  build-types:
  - type: flexspi_nor_debug
    context-map:
      - context: hello_world_cm4.debug
  - type: flexspi_nor_release
    context-map:
      - context: hello_world_cm4.release
  - type: debug
    context-map:
      - context: hello_world_cm7.flexspi_nor_debug
  - type: release
    context-map:
      - context: hello_world_cm7.flexspi_nor_release
  projects:
  - project: cm4/hello_world_cm4.cproject.yml
    for-context:
    - ".debug"
    - ".release"
  - project: cm7/hello_world_cm7.cproject.yml
    not-for-context:
    - ".debug+armgcc"
    - ".release+armgcc"
    - ".debug+mdk"
    - ".release+mdk"
    - ".debug+iar"
    - ".release+iar"

```

**Comment by brondani** [comment]
@Hoohaha It seems there is a misalignment between documentation and implementation.
As expected by the [yml schema](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L118) the `context-map` should not be written as key-value pairs but as a scalar or as list elements. For example:
```
 context-map:
   - HelloCM7.flex_release
```
Please let me know if that fixes your issue.

**Comment by Hoohaha** [comment]
Hi @brondani ,

Without prefix of `context:` the error is gone.
But the cm4 is never built. 
Expected behavior with `context-map` should be:
- hello_world_cm4.debug+mdk
- hello_world_cm7.flexspi_nor_debug+mdk


Command line usage:
`cbuild hello_world_multicore.csolution.yml --update-rte -c .flexspi_nor_debug+mdk --rebuild`

**Comment by brondani** [comment]
@Hoohaha The cm4 will never be built for the context `.flexspi_nor_debug` because it is restricted to `.debug` and `.release` in your example:
```
  - project: cm4/hello_world_cm4.cproject.yml
    for-context:
    - ".debug"
    - ".release"
```
Also the presence of contexts in context-map having build-types that are declared in the same solution sounds just wrong.
The primary goal of context-map is to remap target-types and/or build-types used at project level but not declared at solution level to types that are actually declared at solution level.
Here you can find the discussion that led to this feature:
https://github.com/Open-CMSIS-Pack/devtools/issues/450

**Comment by Hoohaha** [comment]
https://github.com/Open-CMSIS-Pack/devtools/issues/450#issuecomment-1348604652
So, what's the conclusion? 
The implementation of `context-map` is wrong in cbuild?
If yes, What's the fix plan?
We are going to release new version of open cmsis pack which contains multicore examples, that make us confused!

**Comment by brondani** [comment]
@Hoohaha As I mentioned the way you declare contexts in context-map sounds wrong because the remapped build-types are not expected to be also specified among the solution build-types. Remapping non-declared types is ultimately the goal of context-map.
Can you please share a complete solution (all input yml files) and explain what is your goal, so we can try to help you further? Thanks

**Comment by Hoohaha** [comment]
Hi 

Put part of content in here.
hello_world_multicore.csolution.yml:

```yaml
---
solution:
  created-for: cmsis-toolbox@2.0.0
  packs:
  - pack: NXP::MULTICORE
  - pack: NXP::MIMXRT1176_DFP
  - pack: NXP::MIMXRT1170-EVKB_BSP
  - pack: ARM::CMSIS
  target-types:
  - type: armgcc
    compiler: GCC
  - type: iar
    compiler: IAR
  - type: mdk
    compiler: AC6
  output-dirs:
    outdir: "$ProjectDir()$/$TargetType$/$BuildType$"
  build-types:
  - type: flexspi_nor_debug
    context-map:
    - hello_world_cm4.debug
  - type: flexspi_nor_release
    context-map:
    - hello_world_cm4.release
  - type: debug
    context-map:
    - hello_world_cm7.flexspi_nor_debug
  - type: release
    context-map:
    - hello_world_cm7.flexspi_nor_release
  projects:
  - project: cm4/hello_world_cm4.cproject.yml
    not-for-context:
    - ".flexspi_nor_debug+iar"
    - ".flexspi_nor_release+iar"
    - ".flexspi_nor_debug+mdk"
    - ".flexspi_nor_release+mdk"
    - ".flexspi_nor_debug+armgcc"
    - ".flexspi_nor_release+armgcc"
  - project: cm7/hello_world_cm7.cproject.yml
    not-for-context:
    - ".debug+armgcc"
    - ".release+armgcc"
    - ".debug+mdk"
    - ".release+mdk"
    - ".debug+iar"
    - ".release+iar"

```

hello_world_cm4.cproject.yml
```yaml
---
project:
  device: MIMXRT1176DVMAA:cm4
  groups:
  - group: MIMXRT1176/iar
    files:
    - file: iar/MIMXRT1176xxxxx_cm4_ram.icf
      for-compiler:
      - IAR
      for-context:
      - ".debug"
      - ".release"
  - group: MIMXRT1176/arm
    files:
    - file: mdk/MIMXRT1176xxxxx_cm4_ram.scf
      for-compiler:
      - AC6
      for-context:
      - ".debug"
      - ".release"
  - group: MIMXRT1176/gcc
    files:
    - file: armgcc/MIMXRT1176xxxxx_cm4_ram.ld
      for-compiler:
      - GCC
      for-context:
      - ".debug"
      - ".release"
  - group: source
    files:
    - file: hello_world_core1.c
  setups:
  - setup: IAR
    for-compiler: IAR
    for-context: ".debug"
    misc:
    - ASM:
      - "-I$OutDir(hello_world_cm7.flexspi_nor_debug)$"
      - "-DDEBUG"
      - "-D__STARTUP_INITIALIZE_NONCACHEDATA"
      - "-r"
      - "-s"
      - "-M<>"
      - "-w+"
      - "-j"
      C:
      - "-DDEBUG"
      - "-DCPU_MIMXRT1176DVMAA_cm4"
      - "-DFLEXSPI_IN_USE"
      - "-DMCMGR_HANDLE_EXCEPTIONS=1"
      - "-D__SEMIHOST_HARDFAULT_DISABLE=1"
      - "-DMCUXPRESSO_SDK"
      - "-On"
      - "--debug"
      - "--no_cse"
      - "--no_unroll"
      - "--no_inline"
      - "--no_code_motion"
      - "--no_tbaa"
      - "--no_clustering"
      - "--no_scheduling"
      - "--diag_suppress Pa082,Pa050"
      - "-e"
      - "--use_c++_inline"
      CPP:
      - "-DDEBUG"
      - "-DMCUXPRESSO_SDK"
      - "--debug"
      - "--no_cse"
      - "--no_unroll"
      - "--no_code_motion"
      - "--no_tbaa"
      - "--no_clustering"
      - "--no_scheduling"
      - "--diag_suppress Pa082,Pa050"
      - "-e"
      - "--c++"
      Link:
      - "--entry Reset_Handler"
    output:
      base-name: hello_world_cm4
      type: bin
```

hello_world_cm7.cproject.yml
```yaml

---
project:
  device: MIMXRT1176DVMAA:cm7
  groups:
  - group: board
    files:
    - file: board.c
    - file: board.h
    - file: clock_config.c
    - file: clock_config.h
    - file: pin_mux.c
    - file: pin_mux.h
    - file: dcd.c
    - file: dcd.h
  - group: source
    files:
    - file: hello_world_core0.c
  - group: MIMXRT1176/iar
    files:
    - file: iar/MIMXRT1176xxxxx_cm7_flexspi_nor.icf
      for-compiler:
      - IAR
      for-context:
      - ".flexspi_nor_debug"
      - ".flexspi_nor_release"
  - group: MIMXRT1176/arm
    files:
    - file: mdk/MIMXRT1176xxxxx_cm7_flexspi_nor.scf
      for-compiler:
      - AC6
      for-context:
      - ".flexspi_nor_debug"
      - ".flexspi_nor_release"
  - group: MIMXRT1176/gcc
    files:
    - file: armgcc/MIMXRT1176xxxxx_cm7_flexspi_nor.ld
      for-compiler:
      - GCC
      for-context:
      - ".flexspi_nor_debug"
      - ".flexspi_nor_release"
  setups:
  - setup: GCC
    for-compiler: GCC
    for-context: ".flexspi_nor_debug"
    misc:
    - ASM:
      - "-I$ProjectDir()$/../cm4/armgcc/debug"
      - "-I$OutDir(hello_world_cm4.debug)$"
      - "-D__STARTUP_CLEAR_BSS"
      - "-DDEBUG"
      - "-D__STARTUP_INITIALIZE_NONCACHEDATA"
      - "-mcpu=cortex-m7"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "-mthumb"
      C:
      - "-DXIP_EXTERNAL_FLASH=1"
      - "-DXIP_BOOT_HEADER_ENABLE=1"
      - "-DDEBUG"
      - "-DCORE1_IMAGE_COPY_TO_RAM"
      - "-DCPU_MIMXRT1176DVMAA_cm7"
      - "-DMCMGR_HANDLE_EXCEPTIONS=1"
      - "-D__SEMIHOST_HARDFAULT_DISABLE=1"
      - "-DMCUXPRESSO_SDK"
      - "-g"
      - "-O0"
      - "-mcpu=cortex-m7"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "-mthumb"
      - "-MMD"
      - "-MP"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mapcs"
      - "-std=gnu99"
      CPP:
      - "-DDEBUG"
      - "-DCPU_MIMXRT1176DVMAA_cm7"
      - "-DMCUXPRESSO_SDK"
      - "-g"
      - "-O0"
      - "-mcpu=cortex-m7"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "-mthumb"
      - "-MMD"
      - "-MP"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mapcs"
      - "-fno-rtti"
      - "-fno-exceptions"
      Link:
      - "-g"
      - "-mcpu=cortex-m7"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "--specs=nano.specs"
      - "--specs=nosys.specs"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mthumb"
      - "-mapcs"
      - "-Wl,--gc-sections"
      - "-Wl,-static"
      - "-Wl,-z"
      - "-Wl,muldefs"
      - "-Wl,-Map=output.map"
      - "-Wl,--print-memory-usage"
      - "-Wl,--defsym=__use_flash64MB__=1"
      Library:
      - "-lm"
      - "-lc"
      - "-lgcc"
      - "-lnosys"
  - setup: GCC
    for-compiler: GCC
    for-context: ".flexspi_nor_release"
    misc:
    - ASM:
      - "-I$ProjectDir()$/../cm4/armgcc/release"
      - "-I$OutDir(hello_world_cm4.release)$"
      - "-D__STARTUP_CLEAR_BSS"
      - "-DNDEBUG"
      - "-D__STARTUP_INITIALIZE_NONCACHEDATA"
      - "-mcpu=cortex-m7"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "-mthumb"
      C:
      - "-DXIP_EXTERNAL_FLASH=1"
      - "-DXIP_BOOT_HEADER_ENABLE=1"
      - "-DNDEBUG"
      - "-DCORE1_IMAGE_COPY_TO_RAM"
      - "-DCPU_MIMXRT1176DVMAA_cm7"
      - "-DMCMGR_HANDLE_EXCEPTIONS=1"
      - "-D__SEMIHOST_HARDFAULT_DISABLE=1"
      - "-DMCUXPRESSO_SDK"
      - "-Os"
      - "-mcpu=cortex-m7"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "-mthumb"
      - "-MMD"
      - "-MP"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mapcs"
      - "-std=gnu99"
      CPP:
      - "-DNDEBUG"
      - "-DCPU_MIMXRT1176DVMAA_cm7"
      - "-DMCUXPRESSO_SDK"
      - "-Os"
      - "-mcpu=cortex-m7"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "-mthumb"
      - "-MMD"
      - "-MP"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mapcs"
      - "-fno-rtti"
      - "-fno-exceptions"
      Link:
      - "-mcpu=cortex-m7"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv5-d16"
      - "--specs=nano.specs"
      - "--specs=nosys.specs"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mthumb"
      - "-mapcs"
      - "-Wl,--gc-sections"
      - "-Wl,-static"
      - "-Wl,-z"
      - "-Wl,muldefs"
      - "-Wl,-Map=output.map"
      - "-Wl,--print-memory-usage"
      - "-Wl,--defsym=__use_flash64MB__=1"
      Library:
      - "-lm"
      - "-lc"
      - "-lgcc"
      - "-lnosys"
```

**Comment by Hoohaha** [comment]
@brondani 

The goal is hope cbuild can handle the stuffs of context mapping by cbuild itself.

For example, If I build .flexspi_nor_debug+mdk, then the hello_world_cm4.debug+mdk will be build automatically.
`$ cbuild hello_world_multicore.csolution.yml --update-rte -c .flexspi_nor_debug+mdk --rebuild`


Currently, we have a workaround CLI usage for this purpose by passing .debug+mdk,.flexspi_nor_debug+mdk together with option -c
`$ cbuild hello_world_multicore.csolution.yml --update-rte -c .debug+mdk,.flexspi_nor_debug+mdk –rebuild`


The problem of workaround is it’s complex for CI/CV build scripts because it needs to parse the relationship of context-map from csolution.yml by ourselves.

**Comment by brondani** [comment]
@Hoohaha 
Considering your desired command line uses `-c flexspi_nor_debug`, you should write your `build-types` and `projects` in this way in the `hello_world_multicore.csolution.yml` file:
```
  build-types:
  - type: flexspi_nor_debug
    context-map:
      - hello_world_cm4.debug
  - type: flexspi_nor_release
    context-map:
      - hello_world_cm4.release
```

```
  projects:
    - project: cm4/hello_world_cm4.cproject.yml
    - project: cm7/hello_world_cm7.cproject.yml
```

This means when processing the project `hello_world_cm4` for `flexspi_nor_debug` the entries `for-context: .debug` will be accepted and the contexts `hello_world_cm4.flexspi_nor_debug+<target-type>` will be built accordingly.

**Comment by Hoohaha** [comment]
@brondani 

Errors occurred with updated configs:

```yaml

---
solution:
  created-for: cmsis-toolbox@2.0.0
  packs:
  - pack: NXP::MULTICORE
  - pack: NXP::MIMXRT1176_DFP
  - pack: NXP::MIMXRT1170-EVKB_BSP
  - pack: ARM::CMSIS
  target-types:
  - type: armgcc
    compiler: GCC
  - type: iar
    compiler: IAR
  - type: mdk
    compiler: AC6
  output-dirs:
    outdir: "$ProjectDir()$/$TargetType$/$BuildType$"
  build-types:
  - type: flexspi_nor_debug
    context-map:
    - hello_world_cm4.debug
  - type: flexspi_nor_release
    context-map:
    - hello_world_cm4.release
  projects:
  - project: cm4/hello_world_cm4.cproject.yml
  - project: cm7/hello_world_cm7.cproject.yml


```


```
info cbuild: Build Invocation 2.1.0 (C) 2023 Arm Ltd. and Contributors
debug cbuild: CMSIS_PACK_ROOT: C:\Users\NXF60078\AppData\Local\Arm\Packs
debug cbuild: CMSIS_COMPILER_ROOT: C:\Users\NXF60078\AppData\Local\Programs\cmsis-toolbox-windows-amd64\etc
error csolution: context 'hello_world_cm4.debug+armgcc' referenced by access sequence 'OutDir' does not exist
error csolution: processing context 'hello_world_cm4.flexspi_nor_debug+armgcc' failed
C:/Dpc/.workspaces/541aa7/hello_world_cm7.flexspi_nor_debug+armgcc.cprj - info csolution: file generated successfully
C:/Dpc/.workspaces/541aa7/hello_world_cm7.flexspi_nor_debug+armgcc.cbuild.yml - info csolution: file generated successfully
C:/Dpc/.workspaces/541aa7/hello_world_multicore.cbuild-idx.yml - info csolution: file generated successfully
error cbuild: exit status 1

```

**Comment by Hoohaha** [comment]
Changed the access sequence in hello_world_cm7.cproject.yml. Build issue is gone.


```yaml
...
  setups:
  - setup: GCC
    for-compiler: GCC
    for-context: ".flexspi_nor_debug"
    misc:
    - ASM:
      - "-I$ProjectDir()$/../cm4/armgcc/debug"
      - "-I$OutDir(hello_world_cm4)$"   # OLD: "-I$OutDir(hello_world_cm4.debug)$"
   ...
```
